version: '3.8'
services:
  pcs3746:
    build:
      context: ../docker
      cache_from:
        - ubuntu:16.04
        - vhenrique21/pcs3746:latest
    image: vhenrique21/pcs3746:latest 
    container_name: pcs3746-container 
    volumes:  
      - ../linux:/home/student/src/linux 
      - ./initramfs:/home/student/src/initramfs 